// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuUyWcRK7D3LaGnWpv7ye-IHB4geb3bco',
    appId: '1:944705350270:web:f872af65ef1635b5f6862f',
    messagingSenderId: '944705350270',
    projectId: 'workifies',
    authDomain: 'workifies.firebaseapp.com',
    storageBucket: 'workifies.firebasestorage.app',
    measurementId: 'G-HZD6ZVHP4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYDX9BU_M0aYJKRxTl8qcBx22C8Zqql5c',
    appId: '1:944705350270:android:8893dfc1acdc6501f6862f',
    messagingSenderId: '944705350270',
    projectId: 'workifies',
    storageBucket: 'workifies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFQv0fwcO55tYhX9k-mAhzIHN45lUmQE',
    appId: '1:944705350270:ios:f334a33d6e897bebf6862f',
    messagingSenderId: '944705350270',
    projectId: 'workifies',
    storageBucket: 'workifies.firebasestorage.app',
    iosClientId: '944705350270-2tptj1gjksa2vru42e8opov1vms9b6j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.workifies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFQv0fwcO55tYhX9k-mAhzIHN45lUmQE',
    appId: '1:944705350270:ios:f334a33d6e897bebf6862f',
    messagingSenderId: '944705350270',
    projectId: 'workifies',
    storageBucket: 'workifies.firebasestorage.app',
    iosClientId: '944705350270-2tptj1gjksa2vru42e8opov1vms9b6j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.workifies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuUyWcRK7D3LaGnWpv7ye-IHB4geb3bco',
    appId: '1:944705350270:web:a5c95a5f9bfa8f93f6862f',
    messagingSenderId: '944705350270',
    projectId: 'workifies',
    authDomain: 'workifies.firebaseapp.com',
    storageBucket: 'workifies.firebasestorage.app',
    measurementId: 'G-VLDNWEJSED',
  );

}